# Generated by Django 4.0.3 on 2022-05-16 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reply_of_Massage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='unable to retrive', max_length=122, null=True)),
                ('date', models.CharField(default='unable to retrive', max_length=122)),
                ('mymassage', models.TextField()),
                ('replay', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
